changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Notes
    - title: New
      labels:
        - Files
        - Categories
    - title: Fixes
      labels:
        - Files
    - title: Deprecated
      labels:
        - Files